GET http://localhost:3000/api/workouts/

###


POST http://localhost:3000/api/workouts/
Content-Type: application/json

{
    "title":"hello",
    "reps" : 552213,
    "load" : 123123
}

###
POST http://localhost:3000/api/user/signup/
Content-Type: application/json 
 
 {
    "email": "jin@email.com",
    "password": "ABCabc#123"
 }